### PR TITLE
Implement font inter as Base64 svg

### LINKED ISSUE #62: Add font Inter as base64 SVG
**Description**
---
Implement a Metadata component in [/src/components/component/fonts](../blob/main/src/components/component) that returns a base64 encoded version of the [Inter font](https://fonts.google.com/specimen/Inter).

Additional Information
---------------------------
[Easy - Cairo - Low Priority]

**Acceptance Criteria**
---

- [ ] Add the Inter font Metadata component.
- [ ] Implement and pass unit tests (e.g. tests from [here](../blob/main/src/components/component/sdgs/sdg01.cairo#L176))

### PR DESCRIPTION
**Pull request by AryanGodara**
Resolves #62 

To get the base64 encoding, I first downloaded the font, and then used the `Inter-regular.ttf`, (out of Thin, Bold, Italics, etc.)

Then
```bash
$ base64 -i ./file_name > Base64Encoding.txt
```

Then, run a python script to split it into chunks of size 31
```python3
def split_base64_into_chunks(file_path, output_path, chunk_size):
    # read base64encoded data
    with open(file_path, 'r') as file:
        base64_data = file.read()

    # check if base64_data is not empty
    if not base64_data:
        return

    # split  data into chunks of 31
    chunks = [base64_data[i:i+chunk_size] for i in range(0, len(base64_data), chunk_size)]
    print(f"Generated {len(chunks)} chunks.")

    # write chunks to file
    with open(output_path, 'w') as output_file:
        for chunk in chunks:
            output_file.write(f"data.append('{chunk}');\n")
    print("Success!")
```

Then, pasted the `append(<byte64_chunk>)` statements inside inter.cairo

### CODE REVIEW

**Comment by AryanGodara** [comment]
@tekkac Can you please review if this implementation is correct :D

**Comment by tekkac** [comment]
You need to add lines in lib.cairo to incorporate your changes.
If you have time to work on a quick test with a SVG showing it actually works that would be nice too.

**Comment by tekkac** [comment]
Could you update the code so that it passes formatting?

**Comment by AryanGodara** [comment]
> Could you update the code so that it passes formatting?

Yes, sorry. I'll do this asap!

**Review by tekkac — APPROVED** [review]
closes #62

**Pull request merged**
